### PR TITLE
Setup docs search through Algolia

### PR DESCRIPTION
**Pull request by KedziaPawel**
The task cannot be finished at the moment, that's why it is a draft.
In order to finish the setup, it is needed to apply on the Algolia site https://docsearch.algolia.com/apply/ so they will provide apiKey, appId and indexName. The form should be submitted by the owner of the website, as well the docs should be already submitted.

 More info here https://docusaurus.io/docs/search#connecting-algolia

### CODE REVIEW

**Comment by tolbrino** [comment]
Could you provide a functioning implementation which you could test using their free tier account?

**Comment by KedziaPawel** [comment]
> Could you provide a functioning implementation which you could test using their free tier account?
It is a functioning implementation, the search is in the right corner of the navbar. After adding apiKey, appId, and indexName everything will start working. 
Screenshot 2021-12-05 at 13 06 12

**Comment by QYuQianchen** [comment]
@KedziaPawel It seems like we need to deploy the page first before applying for the API key.
> Your website must be production ready. We won't index empty websites nor those filled with placeholder content. Please, wait until you have written some documentation before applying. We would be happy to help you as soon as you have a steady design.

**Comment by tolbrino** [comment]
Approach was clear and used as basis for the current setup. Thus, I close this PR.

**Pull request closed without merging**
